version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: fintech-postgres
    environment:
      POSTGRES_USER: fintech
      POSTGRES_PASSWORD: fintech123
      POSTGRES_DB: fintech_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fintech"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    name: fintech-postgres-data
